# Generated by Django 3.1.6 on 2021-03-01 15:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0010_auto_20210301_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 15, 11, 36, 48642, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 15, 11, 36, 84574, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='list',
            field=models.ForeignKey(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], on_delete=django.db.models.deletion.CASCADE, to='trello_app.tasklist'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 1, 15, 11, 36, 84574, tzinfo=utc)),
        ),
    ]
