# Generated by Django 3.1.6 on 2021-03-03 04:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0013_auto_20210303_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 4, 28, 29, 722883, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 4, 28, 29, 759785, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='list',
            field=models.ForeignKey(choices=[('P', 'PENDING'), ('C', 'COMPLETED'), ('IP', 'IN_PROGRESS'), ('D', 'DROPPED')], on_delete=django.db.models.deletion.CASCADE, to='trello_app.tasklist'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 4, 28, 29, 759785, tzinfo=utc)),
        ),
    ]
